language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: DFy6FAkiqc/dYT8AKYR161r8VzwtPpJkLi7iBZ1k9d2HjXLUzPAUh1Pvy5+A6CnHHxTMz3H8X7Dh3tM4KsgzhBBADWcPjtuBzxta4+V+PgmSHdPcIbLWFiaTWpcq+/pcu68mDTrlvizPbeZmuRGm8lPYsmXwHZoeXlb+fyBxQqy1YN5RmO+IIR+4qPf6YvYS4+B0nz2OGgHJopPV5PE+2MgkNtvzb20wKI7mZRmW87fB4IOI1HuGBao448P4djtQ7JeLeoI66O4kadt771qkGTLf3L/DAHS0FLYJxuKqn4UlLCNSF5mDlIJluIgyFyKXI01f5WbyTfSY2wvMw1lqhEsHx5Uht+DX0tc3RfjnK1Z17m0n4L0kFz24YYEdIS4l2VFTwbBzjr91AEN5vktqR/+5kxGTqGLbpje9h2o5xqZV5V0zadVBgvP+qyFc4jPYLvO7fpG8X4ZCwCwPA6ynvgqtc/tLc5vZpYkSb0MZnKISFM+EPBY4xMNX4dwfQSpBwRuekSEOOsku4Q3Aiq36lD6nF9PwlnHc2Mc8zNNcW/0ZmdkCV3fjAdcj7oF8a53uXzhXXtaXGw/9YEFyc8Km8HV2bgNQf7Ru11JG65/QDTdqpF6f/vcUdDdzh3vxhSxr86umrbeTgnG4hu7Bnb4WNeMZPzeLMgSCxVxyl+ZfD3s=
  app: protected-everglades-84885
  on:
    repo: cellphone4ET/pet-rx
